<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Contract;
use App\Models\Property;
use App\Models\RentPayment;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class ContractController extends Controller
{
    public function index(Request $request)
    {
        $perPage = $request->get('per_page', 15);
        $page = $request->get('page', 1);
        
        $query = Contract::with(['tenant', 'property']);
        
        // Add search functionality if needed
        if ($request->has('search')) {
            $search = $request->get('search');
            $query->where(function($q) use ($search) {
                $q->whereHas('tenant', function ($subQ) use ($search) {
                    $subQ->where('name', 'like', "%{$search}%");
                })->orWhereHas('property', function ($subQ) use ($search) {
                    $subQ->where('name', 'like', "%{$search}%");
                })->orWhere('contract_number', 'like', "%{$search}%");
            });
        }
        
        $contracts = $query->paginate($perPage, ['*'], 'page', $page);
        
        return response()->json([
            'data' => $contracts->items(),
            'current_page' => $contracts->currentPage(),
            'last_page' => $contracts->lastPage(),
            'per_page' => $contracts->perPage(),
            'total' => $contracts->total(),
            'from' => $contracts->firstItem(),
            'to' => $contracts->lastItem(),
        ]);
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'tenant_id' => 'required|exists:tenants,id',
            'property_id' => 'required|exists:properties,id',
            'rent_amount' => 'required|numeric|min:0',
            'start_date' => 'required|date',
            'end_date' => 'nullable|date|after:start_date',
            'number_of_months' => 'nullable|integer|min:1',
            'terms' => 'nullable|string',
            'status' => 'sometimes|in:active,expired,terminated',
        ]);

        // Calculate end_date and total amount from number_of_months if provided
        $numberOfMonths = null;
        if (isset($validated['number_of_months'])) {
            $numberOfMonths = $validated['number_of_months'];
            $startDate = new \DateTime($validated['start_date']);
            $endDate = clone $startDate;
            $endDate->modify('+' . $numberOfMonths . ' months');
            $endDate->modify('-1 day'); // Subtract 1 day to get the last day of the rental period
            $validated['end_date'] = $endDate->format('Y-m-d');
        }

        // Ensure end_date is set
        if (!isset($validated['end_date'])) {
            throw ValidationException::withMessages([
                'end_date' => 'Either end_date or number_of_months must be provided.'
            ]);
        }

        // Calculate number_of_months if not provided (from start_date and end_date)
        if (!isset($numberOfMonths)) {
            $startDate = new \DateTime($validated['start_date']);
            $endDate = new \DateTime($validated['end_date']);
            // Calculate months difference more accurately
            $years = $endDate->diff($startDate)->y;
            $months = $endDate->diff($startDate)->m;
            $days = $endDate->diff($startDate)->d;
            $numberOfMonths = ($years * 12) + $months;
            // If there are remaining days, add 1 month
            if ($days > 0 || $months == 0) {
                $numberOfMonths += 1;
            }
        }

        // Remove number_of_months from validated data (not stored in database)
        unset($validated['number_of_months']);

        // Check if property already has an active contract
        // Use direct Contract query to ensure fresh data from database
        $activeContract = Contract::where('property_id', $validated['property_id'])
            ->where('status', 'active')
            ->where('end_date', '>=', now()->toDateString())
            ->first();
        
        if ($activeContract) {
            throw ValidationException::withMessages([
                'property_id' => 'This property is already leased. Active contract ends on: ' . $activeContract->end_date->format('Y-m-d')
            ]);
        }

        // Create the contract (contract_number will be auto-generated by model boot method)
        $contract = Contract::create($validated);
        
        // Calculate total amount: number_of_months * rent_amount
        $totalAmount = $numberOfMonths * $validated['rent_amount'];
        
        // Create pending payment for the contract
        $startDateObj = new \DateTime($validated['start_date']);
        RentPayment::create([
            'contract_id' => $contract->id,
            'tenant_id' => $validated['tenant_id'],
            'amount' => $totalAmount,
            'month' => $startDateObj->format('Y-m'),
            'payment_date' => $validated['start_date'], // Use start date as payment date
            'payment_method' => 'cash', // Default payment method
            'status' => 'pending',
        ]);

        $contract->load('tenant', 'property', 'rentPayments');

        return response()->json($contract, 201);
    }

    public function show(Contract $contract)
    {
        $contract->load('tenant', 'property');
        return response()->json($contract);
    }

    public function update(Request $request, Contract $contract)
    {
        $validated = $request->validate([
            'tenant_id' => 'sometimes|required|exists:tenants,id',
            'property_id' => 'sometimes|required|exists:properties,id',
            'rent_amount' => 'sometimes|required|numeric|min:0',
            'start_date' => 'sometimes|required|date',
            'end_date' => 'nullable|date',
            'number_of_months' => 'nullable|integer|min:1',
            'terms' => 'nullable|string',
            'status' => 'sometimes|in:active,expired,terminated',
        ]);

        // Calculate end_date from number_of_months if provided
        if (isset($validated['number_of_months'])) {
            $startDate = isset($validated['start_date']) 
                ? new \DateTime($validated['start_date'])
                : new \DateTime($contract->start_date);
            
            $endDate = clone $startDate;
            $endDate->modify('+' . $validated['number_of_months'] . ' months');
            $endDate->modify('-1 day'); // Subtract 1 day to get the last day of the rental period
            $validated['end_date'] = $endDate->format('Y-m-d');
        }

        // Validate end_date is after start_date if both are provided
        $startDate = isset($validated['start_date']) ? $validated['start_date'] : $contract->start_date;
        if (isset($validated['end_date']) && $validated['end_date'] <= $startDate) {
            throw ValidationException::withMessages([
                'end_date' => 'The end date must be after the start date.'
            ]);
        }

        // Remove number_of_months from validated data (not stored in database)
        unset($validated['number_of_months']);

        // If property_id is being changed, check if new property has active contract
        if (isset($validated['property_id']) && $validated['property_id'] != $contract->property_id) {
            $activeContract = Contract::where('property_id', $validated['property_id'])
                ->where('status', 'active')
                ->where('end_date', '>=', now()->toDateString())
                ->where('id', '!=', $contract->id)
                ->first();
            
            if ($activeContract) {
                throw ValidationException::withMessages([
                    'property_id' => 'This property is already leased. Active contract ends on: ' . $activeContract->end_date->format('Y-m-d')
                ]);
            }
        }

        // If status is being set to active, check if property has another active contract
        if (isset($validated['status']) && $validated['status'] === 'active') {
            $propertyId = $validated['property_id'] ?? $contract->property_id;
            $hasOtherActiveContract = Contract::where('property_id', $propertyId)
                ->where('status', 'active')
                ->where('end_date', '>=', now()->toDateString())
                ->where('id', '!=', $contract->id)
                ->exists();
            
            if ($hasOtherActiveContract) {
                throw ValidationException::withMessages([
                    'status' => 'This property already has an active contract. Please terminate or expire the existing contract first.'
                ]);
            }
        }

        $contract->update($validated);
        $contract->load('tenant', 'property');

        return response()->json($contract);
    }

    public function destroy(Contract $contract)
    {
        // Delete associated rent payments first
        RentPayment::where('contract_id', $contract->id)->delete();
        
        // Delete the contract
        $contract->delete();
        
        return response()->json(['message' => 'Contract deleted successfully']);
    }
}
